[package]
name = "shelf"
version = "0.1.0"
authors = ["Brecht Savelkoul <brecht.savelkoul@gmail.com>"]
description = "Simple key-value storage"
license = "MIT"

[lib]
name = "shelf"
path = "src/shelf.rs"
